[FIX] AttributeError: 'ExperimentWriter' object has no attribute 'add_figure'
sktime/pytorch-forecasting pull request #1694
Opened 2024-10-09 08:13 UTC by ewth

### Description

This PR is a bugfix for #1256.

At present, the `AttributeError` is raised (and the script exits) if the logger used does not have the `add_figure` method.

This fix adds a simple check prior to calling `add_figure`.

### Checklist

- [x] Linked issues (if existing)
- [ ] Amended changelog for large changes (and added myself there as contributor)
- [ ] Added/modified tests
- [ ] Used pre-commit hooks when committing to ensure that code is compliant with hooks. Install hooks with `pre-commit install`.
      To run hooks independent of commit, execute `pre-commit run --all-files`

Make sure to have fun coding!

2024-10-09 08:20 UTC, ewth commented
Note that I've added an additional check for `add_embedding`, which causes a similar `AttributeError` if the logger doesn't have the `add_embedding` method.

Although related, it's not _specifically_ about the linked issue. If preferred, I can create a new issue and split that off into it.

2024-10-09 08:27 UTC, ewth commented
I have _not_ run `pre-commit` on these commits -- I was having trouble running the toolchain at all. To "test" the fix I just instantiated the model from the modified Python and ran training on it.

2024-10-09 08:53 UTC, ewth commented
Ah!

I just realised `pre-commit` was installed at a system level, not in the environment I was using. I can now run it successfully.

Running it on this branch produces the following:

```text

$ pre-commit run --all-files
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...............................................................Passed
check python ast.........................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

examples/ar.py:88:56: E226 missing whitespace around arithmetic operator
print(f"Number of parameters in network: {deepar.size()/1e3:.1f}k")
                                                       ^
examples/nbeats.py:68:53: E226 missing whitespace around arithmetic operator
print(f"Number of parameters in network: {net.size()/1e3:.1f}k")
                                                    ^
examples/stallion.py:122:53: E226 missing whitespace around arithmetic operator
print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")
                                                    ^
pytorch_forecasting/data/timeseries.py:106:28: E226 missing whitespace around arithmetic operator
                f"{na} ({na/tensor.size(0):.2%}) of {name} "
                           ^

isort....................................................................Passed
black....................................................................Passed
nbqa-black...............................................................Passed
nbqa-isort...............................................................Passed
nbqa-flake8..............................................................Failed
- hook id: nbqa-flake8
- exit code: 1

docs/source/tutorials/stallion.ipynb:cell_7:25:53: E226 missing whitespace around arithmetic operator
print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")
                                                    ^
docs/source/tutorials/stallion.ipynb:cell_9:29:53: E226 missing whitespace around arithmetic operator
print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")
                                                    ^

nbqa-check-ast...........................................................Passed
```

Which is the same result as running it on `main`:

```text

trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...............................................................Passed
check python ast.........................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

examples/ar.py:88:56: E226 missing whitespace around arithmetic operator
print(f"Number of parameters in network: {deepar.size()/1e3:.1f}k")
                                                       ^
examples/nbeats.py:68:53: E226 missing whitespace around arithmetic operator
print(f"Number of parameters in network: {net.size()/1e3:.1f}k")
                                                    ^
examples/stallion.py:122:53: E226 missing whitespace around arithmetic operator
print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")
                                                    ^
pytorch_forecasting/data/timeseries.py:106:28: E226 missing whitespace around arithmetic operator
                f"{na} ({na/tensor.size(0):.2%}) of {name} "
                           ^

isort....................................................................Passed
black....................................................................Passed
nbqa-black...............................................................Passed
nbqa-isort...............................................................Passed
nbqa-flake8..............................................................Failed
- hook id: nbqa-flake8
- exit code: 1

docs/source/tutorials/stallion.ipynb:cell_7:25:53: E226 missing whitespace around arithmetic operator
print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")
                                                    ^
docs/source/tutorials/stallion.ipynb:cell_9:29:53: E226 missing whitespace around arithmetic operator
print(f"Number of parameters in network: {tft.size()/1e3:.1f}k")
                                                    ^

nbqa-check-ast...........................................................Passed
```

2024-10-09 09:17 UTC, ewth commented
I've created #1695 and #1696 as a result of the above.

2024-10-09 13:25 UTC, fkiraly commented
Hm, question - is this an issue if `lightning >=2`, or only on `lightning <2`?

Because currently, `pyproject.toml` does not officially support `lightning <2`.

Nothing wrong with more defensive programming, but it feels like there is a larger issue to discuss about `lightning <2` support if this is the case.

2024-10-09 15:32 UTC, ewth commented
It impacts me with `lightning==2.4.0`.

2024-10-13 21:57 UTC, fkiraly commented
But that would mean the functionality is *no longer* available on higher lightning versions?

We need to understand then the version range this issue appears on, the exact condition when it occurs, and why we are currently not seeing it in the tests: the version in the CI is `lightning 2.4.0`.

I believe we are covering and executing the code in question?

2024-10-18 05:16 UTC, fkiraly commented
@ewth, ping - could you kindly explain the exact condition under which the issue arises that you are fixing? I cannot reproduce the error, and there does not seem to be a bug report.

2024-10-18 05:21 UTC, fkiraly requested changes
Looks good to me.

May I request some small things:

* the `hasattr` check assumes `logger` has an attr `experiment`. Is this even always true? Given the unclear interface changes to the loggers, I would just be more defensive, and check that `logger` has `experiment` *and* that has `add_figure`.
* there is now a lot of duplicated code, not very DRY. May I suggest to move this to the base model into a function `_logger_supports(fun : str)`? The `fun` is a string that can be `"add_figure"` or `"add_experiment"`. For `"add_figure"`, we would check both that `matplotlib` is present, and carry out the new check.

2024-10-22 03:43 UTC, ewth commented
@fkiraly I’ve been buried in work — I haven’t abandoned this, and will return to it as soon as I am able (hopefully this week sometime).

2024-10-22 08:20 UTC, fkiraly commented
sure, no rush. Worst case, it is very close to the finish line and a maintainer will wrap it up sometime.

2024-11-06 12:19 UTC, fkiraly commented
@ewth, are you still planning to wrap this up? We are approaching a new release.

2024-11-11 16:09 UTC, fkiraly approved these changes
I made the requested changes now so this can go into the release. Thanks for your work, @ewth!

2024-11-11 16:47 UTC, merged

2024-11-12 07:39 UTC, ewth commented
Thanks @fkiraly! Sorry I haven't been able to get back to it, 110% of my time has been consumed.